chore: disable continue-on-error in CI

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -23,35 +23,39 @@ jobs:
 
       - name: Check Code Formatting
         run: mise :format:check
-        id: format
-        continue-on-error: true
+        # id: format
+        # continue-on-error: true
 
       - name: Lint Code
         run: mise :lint
-        id: lint
-        continue-on-error: true
+        # id: lint
+        # continue-on-error: true
 
       - name: Run Unit Tests
         run: mise :test/unit
-        id: test-unit
-        continue-on-error: true
+        # id: test-unit
+        # continue-on-error: true
 
       - name: Run System Tests
         run: mise :test/system
-        id: test-system
-        continue-on-error: true
+        # id: test-system
+        # continue-on-error: true
 
       - name: Save Cache
         if: always()
         uses: ./.github/actions/cache-save
 
-      - name: Fail if QA Failed
-        if: |
-          steps.format.outcome == 'failure' ||
-          steps.lint.outcome == 'failure' ||
-          steps.test-unit.outcome == 'failure' ||
-          steps.test-system.outcome == 'failure'
-        run: exit 1
+      # TODO: Re-enable continue-on-error if GitHub ever addresses the problem:
+      # - https://github.com/orgs/community/discussions/15452
+      # - https://github.com/actions/runner/issues/2347
+
+      # - name: Fail if QA Failed
+      #   if: |
+      #     steps.format.outcome == 'failure' ||
+      #     steps.lint.outcome == 'failure' ||
+      #     steps.test-unit.outcome == 'failure' ||
+      #     steps.test-system.outcome == 'failure'
+      #   run: exit 1
 
   build:
     name: Build
